---
name: gisty

"on":
  schedule:
    - cron: "*/5 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2.3.2
      - run: |
          pip install -r requirements.txt
      - run: |
          ./run.py kornicameister \
            ${{ secrets.MIGHTY_TOKEN }} \
            ${{ secrets.GIST_ID }} \
            ${{ secrets.GIST_TOKEN }}
